{"timestamp":"2025-07-11T21:48:38.055864","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T21:48:38.056043","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/bank_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T21:48:38.075041Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:38.075157Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:38.075237Z","level":"info","event":"Current task name:extract_transform_load","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:38.075308Z","level":"info","event":"Dag name:bank_data_etl_process","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:38.083185","level":"info","event":"Connection Retrieved 'postgres_bank_ds'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-11T21:48:38.083748","level":"info","event":"Пауза 5 секунд для наглядности логов...","logger":"root"}
{"timestamp":"2025-07-11T21:48:43.085066","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_account_d.csv для таблицы MD_ACCOUNT_D =====","logger":"root"}
{"timestamp":"2025-07-11T21:48:43.111329","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:76: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T21:48:43.168060","level":"error","event":"ОШИБКА ВНУТРИ ETL ЗАДАЧИ: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1)\n\n[SQL: INSERT INTO \"DS\".\"MD_ACCOUNT_D\" (\"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\") SELECT \"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\" FROM \"DS\".\"temp_md_account_d\" ON CONFLICT (\"account_rk\", \"data_actual_date\") DO UPDATE SET \"data_actual_end_date\" = EXCLUDED.\"data_actual_end_date\", \"account_number\" = EXCLUDED.\"account_number\", \"char_type\" = EXCLUDED.\"char_type\", \"currency_rk\" = EXCLUDED.\"currency_rk\", \"currency_code\" = EXCLUDED.\"currency_code\";]\n(Background on this error at: https://sqlalche.me/e/14/9h9h)","logger":"root"}
{"timestamp":"2025-07-11T21:48:43.169081Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.169196Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.169311Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): extract_transform_load>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.169411Z","level":"info","event":"Failure caused by ETL процесс провалился с ошибкой: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1)","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.169504Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.169588Z","level":"info","event":"[SQL: INSERT INTO \"DS\".\"MD_ACCOUNT_D\" (\"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\") SELECT \"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\" FROM \"DS\".\"temp_md_account_d\" ON CONFLICT (\"account_rk\", \"data_actual_date\") DO UPDATE SET \"data_actual_end_date\" = EXCLUDED.\"data_actual_end_date\", \"account_number\" = EXCLUDED.\"account_number\", \"char_type\" = EXCLUDED.\"char_type\", \"currency_rk\" = EXCLUDED.\"currency_rk\", \"currency_code\" = EXCLUDED.\"currency_code\";]","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.169756Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/9h9h)","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:48:43.168185","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowFailException","exc_value":"ETL процесс провалился с ошибкой: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1)\n\n[SQL: INSERT INTO \"DS\".\"MD_ACCOUNT_D\" (\"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\") SELECT \"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\" FROM \"DS\".\"temp_md_account_d\" ON CONFLICT (\"account_rk\", \"data_actual_date\") DO UPDATE SET \"data_actual_end_date\" = EXCLUDED.\"data_actual_end_date\", \"account_number\" = EXCLUDED.\"account_number\", \"char_type\" = EXCLUDED.\"char_type\", \"currency_rk\" = EXCLUDED.\"currency_rk\", \"currency_code\" = EXCLUDED.\"currency_code\";]\n(Background on this error at: https://sqlalche.me/e/14/9h9h)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":100,"name":"extract_transform_load"}],"is_group":false,"exceptions":[]},{"exc_type":"DataError","exc_value":"(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1)\n\n[SQL: INSERT INTO \"DS\".\"MD_ACCOUNT_D\" (\"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\") SELECT \"data_actual_date\", \"data_actual_end_date\", \"account_rk\", \"account_number\", \"char_type\", \"currency_rk\", \"currency_code\" FROM \"DS\".\"temp_md_account_d\" ON CONFLICT (\"account_rk\", \"data_actual_date\") DO UPDATE SET \"data_actual_end_date\" = EXCLUDED.\"data_actual_end_date\", \"account_number\" = EXCLUDED.\"account_number\", \"char_type\" = EXCLUDED.\"char_type\", \"currency_rk\" = EXCLUDED.\"currency_rk\", \"currency_code\" = EXCLUDED.\"currency_code\";]\n(Background on this error at: https://sqlalche.me/e/14/9h9h)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":93,"name":"extract_transform_load"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1385,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py","lineno":334,"name":"_execute_on_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1577,"name":"_execute_clauseelement"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"StringDataRightTruncation","exc_value":"value too long for type character varying(1)\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
