{"timestamp":"2025-07-11T21:51:48.633308","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T21:51:48.633833","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/bank_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T21:51:48.659188Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:48.659343Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:48.659443Z","level":"info","event":"Current task name:extract_transform_load","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:48.659541Z","level":"info","event":"Dag name:bank_data_etl_process","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:48.667455","level":"info","event":"Connection Retrieved 'postgres_bank_ds'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-11T21:51:48.668045","level":"info","event":"Пауза 5 секунд для наглядности логов...","logger":"root"}
{"timestamp":"2025-07-11T21:51:53.670242","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_account_d.csv для таблицы MD_ACCOUNT_D с кодировкой cp1251 =====","logger":"root"}
{"timestamp":"2025-07-11T21:51:53.697174","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:73: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T21:51:53.764796","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_currency_d.csv для таблицы MD_CURRENCY_D с кодировкой utf-8-sig =====","logger":"root"}
{"timestamp":"2025-07-11T21:51:53.766192","level":"error","event":"ОШИБКА ВНУТРИ ETL ЗАДАЧИ: 'utf-8' codec can't decode byte 0x98 in position 1189: invalid start byte","logger":"root"}
{"timestamp":"2025-07-11T21:51:53.766332","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowFailException","exc_value":"ETL процесс провалился с ошибкой: 'utf-8' codec can't decode byte 0x98 in position 1189: invalid start byte","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":96,"name":"extract_transform_load"}],"is_group":false,"exceptions":[]},{"exc_type":"UnicodeDecodeError","exc_value":"'utf-8' codec can't decode byte 0x98 in position 1189: invalid start byte","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":69,"name":"extract_transform_load"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":948,"name":"read_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":611,"name":"_read"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":1448,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":1723,"name":"_make_engine"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py","lineno":93,"name":"__init__"},{"filename":"/opt/airflow/parsers.pyx","lineno":579,"name":"pandas._libs.parsers.TextReader.__cinit__"},{"filename":"/opt/airflow/parsers.pyx","lineno":668,"name":"pandas._libs.parsers.TextReader._get_header"},{"filename":"/opt/airflow/parsers.pyx","lineno":879,"name":"pandas._libs.parsers.TextReader._tokenize_rows"},{"filename":"/opt/airflow/parsers.pyx","lineno":890,"name":"pandas._libs.parsers.TextReader._check_tokenize_status"},{"filename":"/opt/airflow/parsers.pyx","lineno":2050,"name":"pandas._libs.parsers.raise_parser_error"},{"filename":"<frozen codecs>","lineno":322,"name":"decode"},{"filename":"/usr/local/lib/python3.12/encodings/utf_8_sig.py","lineno":69,"name":"_buffer_decode"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-11T21:51:53.768250Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:53.768364Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:53.768450Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): extract_transform_load>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T21:51:53.768544Z","level":"info","event":"Failure caused by ETL процесс провалился с ошибкой: 'utf-8' codec can't decode byte 0x98 in position 1189: invalid start byte","chan":"stdout","logger":"task"}
